# Generated by Django 6.1.1 on 2026-09-18 10:50

import django.core.validators
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('jersey_number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name='Игровой номер')),
                ('position', models.CharField(choices=[('GK', 'Вратарь'), ('DF', 'Защитник'), ('MF', 'Полузащитник'), ('FW', 'Нападающий')], max_length=2, verbose_name='Позиция')),
                ('club', models.CharField(max_length=100, verbose_name='Клуб')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='players/', verbose_name='Фотография')),
                ('birth_date', models.DateField(blank=True, null=True, validators=[main.models.validate_not_in_future], verbose_name='Дата рождения')),
                ('nationality', models.CharField(blank=True, max_length=100, verbose_name='Гражданство')),
                ('height_cm', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(250)], verbose_name='Рост (см)')),
                ('weight_kg', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(250)], verbose_name='Вес (кг)')),
                ('appearances', models.PositiveIntegerField(default=0, verbose_name='Матчи')),
                ('goals', models.PositiveIntegerField(default=0, verbose_name='Голы')),
                ('assists', models.PositiveIntegerField(default=0, verbose_name='Голевые передачи')),
            ],
            options={
                'verbose_name': 'Игрок',
                'verbose_name_plural': 'Игроки',
                'ordering': ('club', 'jersey_number', 'last_name', 'first_name'),
                'constraints': [models.UniqueConstraint(fields=('club', 'jersey_number'), name='unique_jersey_number_per_club')],
            },
        ),
    ]
